#!/bin/sh

xqr() {
    colo="$(xrdb -q | grep -w "color$1")"
    printf '%s' ${colo##*:}
}

silent="$(xqr 0)"
pr="$(xqr 0)"
fg="$(xqr 10)"
gr="$(xqr 10)"

berryc border_width       0
berryc inner_border_width 0
berryc title_height       0
berryc edge_gap 45 0 0 0

berryc smart_place "true"
berryc edge_lock   "true"

berryc focus_color   "${fg###}"
berryc unfocus_color "${gr###}"

berryc inner_focus_color   "${pr###}"
berryc inner_unfocus_color "${gr###}"

berryc text_focus_color   "${silent###}"
berryc text_unfocus_color "${gr###}"

berryc set_font ibmplexmonomedium-11
